theme: jekyll-theme-tactiletitle: Cloudowski.com Helm Charts
description: A chart repo for storing charts.
url: "https://cloudowski.github.io/helm-charts/"
repo_name: cloudowski

exclude:
  - Gemfile
  - Gemfile.lock
  - .gitignore
